#!/usr/bin/env python3
"""Regenerate .claude-plugin/plugin.json and every bucket README from the tree.

The frontmatter in each SKILL.md is the single source of truth for descriptions,
so `./scripts/gen-docs.py` after adding a skill is all it takes to keep the
manifest and the docs honest.

Usage:
  ./scripts/gen-docs.py            # rewrite manifest + bucket READMEs
  ./scripts/gen-docs.py --check    # exit 1 if anything is out of date (for CI)
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"

BUCKET_TITLES = {
    "engineering": ("Engineering", "Writing, reviewing, testing, and documenting code."),
    "web": ("Web quality", "Performance, accessibility, SEO, and Core Web Vitals audits."),
    "ruflo": ("Ruflo", "Swarm, autopilot, and neural-routing skills for the Ruflo plugin suite."),
    "hookify": ("Hookify", "Create and manage hooks that stop unwanted agent behaviour."),
    "nvidia": ("NVIDIA / AI stack", "RAG Blueprint, NeMo, AI-Q, Nemotron, and DGX Spark workflows."),
    "productivity": ("Productivity", "Non-code workflow: comms, context hygiene, SaaS connections."),
    "misc": ("Misc", "Kept around, used occasionally."),
}
# Buckets that exist for staging and must never reach the manifest or the docs.
PRIVATE_BUCKETS = {"personal", "in-progress", "deprecated"}


def skill_md(d: Path) -> Path | None:
    for n in ("SKILL.md", "skill.md"):
        if (d / n).is_file():
            return d / n
    return None


def frontmatter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    body = m.group(1) if m else ""
    name = re.search(r"^name:\s*(.+)$", body, re.M)
    desc = re.search(r"^description:\s*(\|-?|>-?)?\s*(.*(?:\n[ \t]+.*)*)$", body, re.M)
    d = " ".join(desc.group(2).split()) if desc else ""
    d = d.strip().strip('"').strip("'")
    return (name.group(1).strip() if name else path.parent.name, d)


def first_sentence(d: str, limit: int = 150) -> str:
    d = re.sub(r"\s+", " ", d).strip()
    cut = re.split(r"(?<=[.!?])\s+(?=[A-Z“\"])", d)
    s = cut[0] if cut else d
    if len(s) > limit:
        s = s[: limit - 1].rsplit(" ", 1)[0] + "…"
    return s


def scan() -> dict[str, list[tuple[str, str, str]]]:
    """-> {bucket: [(name, description, repo_relative_path_to_SKILL.md)]}"""
    out: dict[str, list[tuple[str, str, str]]] = {}
    for bucket_dir in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        bucket = bucket_dir.name
        if bucket in PRIVATE_BUCKETS:
            continue
        if skill_md(bucket_dir):  # a skill sitting at skills/ root
            out.setdefault("misc", [])
            name, desc = frontmatter(skill_md(bucket_dir))
            out["misc"].append((name, desc, str(skill_md(bucket_dir).relative_to(ROOT))))
            continue
        for child in sorted(p for p in bucket_dir.iterdir() if p.is_dir()):
            md = skill_md(child)
            if not md:
                continue
            name, desc = frontmatter(md)
            out.setdefault(bucket, []).append((name, desc, str(md.relative_to(ROOT))))
    return out


def build_manifest(buckets) -> str:
    skills = []
    for bucket in sorted(buckets):
        for _name, _desc, path in buckets[bucket]:
            skills.append("./" + os.path.dirname(path))
    agents = sorted(
        "./" + str(p.relative_to(ROOT))
        for p in (ROOT / "agents").glob("*.md")
        if p.name != "README.md"
    )
    commands = sorted(
        "./" + str(p.relative_to(ROOT))
        for p in (ROOT / "commands").glob("*.md")
        if p.name != "README.md"
    )
    manifest = {
        "name": "ClaudeSkills-Neronain",
        "version": "2.0.0",
        "description": (
            "Personal Claude Code setup: skills, subagents, slash commands, "
            "the RTK token-saving hook, and MCP server configs."
        ),
        "author": {"name": "neronain"},
        "homepage": "https://github.com/neronain/ClaudeSkills-Neronain",
        "skills": skills,
        "agents": agents,
        "commands": commands,
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def build_bucket_readme(bucket: str, entries) -> str:
    title, blurb = BUCKET_TITLES.get(bucket, (bucket.title(), ""))
    lines = [f"# {title} skills", "", blurb, "", f"{len(entries)} skills in this bucket.", "", "| Skill | What it does |", "|---|---|"]
    for name, desc, path in sorted(entries):
        rel = os.path.relpath(path, f"skills/{bucket}")
        lines.append(f"| [`{name}`]({rel}) | {first_sentence(desc)} |")
    lines += [
        "",
        "---",
        "",
        "Generated by `scripts/gen-docs.py` — edit the `description:` in each `SKILL.md`, not this file.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    buckets = scan()
    stale = []

    targets: list[tuple[Path, str]] = [
        (ROOT / ".claude-plugin" / "plugin.json", build_manifest(buckets))
    ]
    for bucket, entries in buckets.items():
        targets.append((SKILLS / bucket / "README.md", build_bucket_readme(bucket, entries)))

    for path, content in targets:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    total = sum(len(v) for v in buckets.values())
    if check and stale:
        print("out of date:\n  " + "\n  ".join(stale), file=sys.stderr)
        print("run ./scripts/gen-docs.py", file=sys.stderr)
        return 1
    print(f"{total} skills across {len(buckets)} buckets" + (" — up to date" if check else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
